name: Generate README

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ruby
        run: sudo apt install ruby-full

      - name: Install Asciidoctor
        run: |
          sudo gem install asciidoctor  # Install the Asciidoctor gem
          sudo gem install asciidoctor-reducer

      - name: Create HTMLs
        run: |
          find . -type f -name "*.html" -exec rm -f {} \;
          # Create or clear README-NEW.md
          > README-HTML.md
          > README.md
          echo "# Contents" >> README-HTML.md
          echo "# Contents" >> README.md
          pwd
          ls
          # Iterate over directories containing .adoc files (up to maxdepth 2)
          for dir in $(find . -maxdepth 2 -type f -name "*.adoc" -exec dirname {} \; | sort -u); do
            # Only process directories one level deep in the repo
            if [[ $(echo "$dir" | grep -o '/' | wc -l) -eq 1 ]]; then
              echo "Processing directory: $dir"

              # Create master.adoc file
              master_adoc="$dir/master-raw.adoc"
              cleaned_dir=$(basename "$dir")
              echo "=  $cleaned_dir" > "$master_adoc"  # Add a title to the master file

              # Append all .adoc files in the directory to the master.adoc file
              for file in $(find "$dir" -maxdepth 1 -type f -name "*.adoc" | sort -u); do
                echo "$file"
                if ! echo "$file" | grep -q "master" && echo "$file" | grep -q "raw"; then
                  cleaned_file=$(basename "$file")
                  echo "include::$cleaned_file[]" >> "$master_adoc"
                fi
              done
              cat  "$dir/master-raw.adoc"
              echo "$master_adoc"
              # Generate HTML from master.adoc
              pwd
              asciidoctor "$master_adoc"
              asciidoctor-reducer "$master_adoc" > "$dir/master.adoc" 
              # Remove the temporary master.adoc file after processing

              # Add section for this directory in README-NEW.md
              echo "## [cleaned_dir] ($dir/master.html)" >> README-HTML.md
              echo "## [cleaned_dir] ($dir/master.adoc)" >> README.md
              asciidoctor **/*.adoc
              # Find all HTML files in the directory and append them to README-NEW.md
              for html_file in $(find "$dir" -name "*.html" | sort); do
                if [ -f "$html_file" ]; then
                  if ! echo "$html_file" | grep -q "master.html"; then
                    clean_file=$(basename "$html_file")
                    echo "### [clean_file]($html_file)" >> README-HTML.md
                    asciidoctor-reducer -o "$dir/$clean_file.adoc"
                    echo "### [clean_file]($dir/$clean_file.adoc)" >> README.md
                  fi
                fi
              done
            fi
          done

          # Print the generated README content for debugging
          cat README-NEW.md
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "github-action commit"
          git push origin main

      - name: Upload HTML files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-output
          path: '**/*.html'

      - name: Upload README file as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: README-NEW
          path: '**/*.md'