name: Generate README

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ruby
        run: sudo apt install ruby-full

      - name: Install Asciidoctor
        run: |
          sudo gem install asciidoctor  # Install the Asciidoctor gem
          sudo gem install asciidoctor-reducer

      - name: Create HTMLs
        run: |
          find . -type f -name "*.html" -exec rm -f {} \;
          > README-HTML.md
          > README.md
          echo "= Contents" >> README-HTML.adoc
          echo "# Contents" >> README.md

          for dir in $(find . -maxdepth 2 -type f -name "*.adoc" -exec dirname {} \; | sort -u); do
            find $dir -maxdepth 1 -type f -name "*.adoc" ! -name "*raw*" -exec rm {} +
            if [[ $(echo "$dir" | grep -o '/' | wc -l) -eq 1 ]]; then
              echo "Processing directory: $dir"

              master_adoc="$dir/master-raw.adoc"
              cleaned_dir=$(basename "$dir")
              echo "=  $cleaned_dir" > "$master_adoc"
              echo "" >> "$master_adoc"

              for file in $(find "$dir" -maxdepth 1 -type f -name "*.adoc" | sort -u); do
                if ! echo "$file" | grep -q "master" && echo "$file" | grep -q "raw"; then
                  cleaned_file=$(basename "$file")
                  echo "include::$cleaned_file[]" >> "$master_adoc"
                  echo "" >> "$master_adoc"
                fi
              done

              asciidoctor "$master_adoc"
              asciidoctor-reducer "$master_adoc" > "$dir/master.adoc" 

              if [[ "$cleaned_dir" == *.* ]]; then
                after_dot="${cleaned_dir#*.}"
                echo "== $dir/master.html[$after_dot]" >> README-HTML.adoc
                echo "## [$after_dot]($dir/master.adoc)" >> README.md
              else
                echo "== $dir/master.html[$cleaned_dir]" >> README-HTML.adoc
                echo "## [$cleaned_dir]($dir/master.adoc)" >> README.md
              fi
              
              for adoc_file in $(find $dir -maxdepth 1 -type f -name "*.adoc" | sort -u); do
                if [ -f "$adoc_file" ]; then
                  if ! echo "$adoc_file" | grep -q "master.adoc" && ! echo "$adoc_file" | grep -q "master-raw.adoc"; then
                    clean_file=$(basename "$adoc_file")
                    first_value="${clean_file%%-*}"
                    if [[ "$first_value" == *.* ]]; then
                      after_dot="${first_value#*.}"
                      asciidoctor-reducer "$dir/$clean_file" > "$dir/$first_value.adoc" 
                      asciidoctor "$dir/$clean_file"
                      echo "- [$after_dot]($dir/$first_value.adoc)" >> README.md
                      echo "- $dir/$first_value-raw.html[$after_dot]" >> README-HTML.adoc
                    else
                      asciidoctor-reducer "$dir/$clean_file" > "$dir/$first_value.adoc" 
                      asciidoctor "$dir/$clean_file"
                      echo "- [$first_value]($dir/$first_value.adoc)" >> README.md
                      echo "- $dir/$first_value-raw.html[$first_value]" >> README-HTML.adoc
                    fi
                  fi
                fi
              done
            fi
          done
          asciidoctor README-HTML.adoc
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "github-action commit"
          git push origin main