name: Generate README

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ruby
        run: sudo apt install ruby-full

      - name: Install Asciidoctor
        run: |
          sudo gem install asciidoctor  # Install the Asciidoctor gem
          sudo gem install asciidoctor-reducer

      - name: Create HTMLs
        run: |
          find . -type f -name "*.html" -exec rm -f {} \;
          > README-HTML.md
          > README.md
          echo "# Contents" >> README-HTML.md
          echo "# Contents" >> README.md

          for dir in $(find . -maxdepth 2 -type f -name "*.adoc" -exec dirname {} \; | sort -u); do
            find $dir -maxdepth 1 -type f -name "*.adoc" ! -name "*raw*" -exec rm {} +
            if [[ $(echo "$dir" | grep -o '/' | wc -l) -eq 1 ]]; then
              echo "Processing directory: $dir"

              master_adoc="$dir/master-raw.adoc"
              cleaned_dir=$(basename "$dir")
              echo "=  $cleaned_dir" > "$master_adoc"
              echo "---" >> "$master_adoc"

              for file in $(find "$dir" -maxdepth 1 -type f -name "*.adoc" | sort -u); do
                if ! echo "$file" | grep -q "master" && echo "$file" | grep -q "raw"; then
                  cleaned_file=$(basename "$file")
                  echo "include::$cleaned_file[]" >> "$master_adoc"
                fi
              done
              cat  "$dir/master-raw.adoc"
              echo "$master_adoc"

              asciidoctor "$master_adoc"
              asciidoctor-reducer "$master_adoc" > "$dir/master.adoc" 

              if [[ "$cleaned_dir" == *.* ]]; then
                after_dot="${cleaned_dir#*.}"
                echo $after_dot

                echo "## [$after_dot]($dir/master.html)" >> README-HTML.md
                echo "## [$after_dot]($dir/master.adoc)" >> README.md
              else
                echo "## [$cleaned_dir]($dir/master.html)" >> README-HTML.md
                echo "## [$cleaned_dir]($dir/master.adoc)" >> README.md
              fi

              cat README.md
              asciidoctor **/*.adoc

              for html_file in $(find "$dir" -name "*.html" | sort); do
                if [ -f "$html_file" ]; then
                  if ! echo "$html_file" | grep -q "master.html" && ! echo "$html_file" | grep -q "master-raw.html"; then
                    if echo "$html_file" | grep -q "*-raw.html"; then
                      clean_file=$(basename "$html_file")
                      first_value="${clean_file%%-*}"
                      filename_without_extension=$(echo "$first_value" | sed 's/\.html$//')
                      if [[ "$filename_without_extension" == *.* ]]; then
                        after_dot="${filename_without_extension#*.}"
                        echo "- [$after_dot]($html_file)" >> README-HTML.md
                      else
                        echo "- [$filename_without_extension]($html_file)" >> README-HTML.md
                      fi
                    fi
                  fi
                fi
              done

              for adoc_file in $(find $dir -maxdepth 1 -type f -name "*.adoc" | sort -u); do
                if [ -f "$adoc_file" ]; then
                  if ! echo "$adoc_file" | grep -q "master.adoc" && ! echo "$adoc_file" | grep -q "master-raw.adoc"; then
                    clean_file=$(basename "$adoc_file")
                    first_value="${clean_file%%-*}"
                    if [[ "$first_value" == *.* ]]; then
                      after_dot="${first_value#*.}"
                      asciidoctor-reducer "$dir/$clean_file" > "$dir/$first_value.adoc" 
                      echo "- [$after_dot]($dir/$first_value.adoc)" >> README.md
                    else
                      asciidoctor-reducer "$dir/$clean_file" > "$dir/$first_value.adoc" 
                      echo "- [$first_value]($dir/$first_value.adoc)" >> README.md
                    fi
                  fi
                fi
              done
            fi
          done

          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "github-action commit"
          git push origin main