name: Generate README
on:
  push:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Ruby
      run: sudo apt install ruby-full
    - name: Install Asciidoctor
      run: sudo gem install asciidoctor
    - name: Create HTMLs
      run: |
        > README-NEW.md
        echo "# Contents" >> README-NEW.md
        for dir in $(find . -maxdepth 2 -type f -name "*.adoc" -exec dirname {} \; | sort -u); do
          if [[ $(echo "$dir" | grep -o '/' | wc -l) -eq 1 ]]; then
            echo "Processing directory: $dir"

            master_adoc="$dir/master.adoc"
            echo "=  $dir" > "$master_adoc"

            for file in $(find "$dir" -name "*.adoc"); do
              echo "include::${file}[]" >> "$master_adoc"
              echo "" >> "$master_adoc"
            done

            asciidoctor "$master_adoc"

            rm "$master_adoc"

            echo "## [$dir] (~/$dir/master.html)" >> README-NEW.md

            cd $dir
            asciidoctor **/*.adoc

            for html_file in $(ls "$dir"/*.html | sort); do
              if [ -f "$html_file" ]; then
                echo "### [$html_file](~/$dir/$html_file)" >> README-NEW.md
              fi
            done
          fi
        done
        cat README-NEW.md
      - name: Upload HTML files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html-output
          path: '**/*.html'
