name: Generate README

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ruby
        run: sudo apt install ruby-full

      - name: Install Asciidoctor
        run: |
          sudo gem install asciidoctor  # Install the Asciidoctor gem
          sudo gem install asciidoctor-reducer

      - name: Create HTMLs
        run: |
          find . -type f -name "*.html" -exec rm -f {} \;
          
          > README-HTML.md
          > README.md
          echo "# Contents" >> README-HTML.md
          echo "# Contents" >> README.md

          for dir in $(find . -maxdepth 2 -type f -name "*.adoc" -exec dirname {} \; | sort -u); do
            if [[ $(echo "$dir" | grep -o '/' | wc -l) -eq 1 ]]; then
              echo "Processing directory: $dir"

              master_adoc="$dir/master-raw.adoc"
              cleaned_dir=$(basename "$dir")
              echo "=  $cleaned_dir\n" > "$master_adoc"

              for file in $(find "$dir" -maxdepth 1 -type f -name "*.adoc" | sort -u); do
                echo "$file"
                if ! echo "$file" | grep -q "master" && echo "$file" | grep -q "raw"; then
                  cleaned_file=$(basename "$file")
                  echo "include::$cleaned_file[]\n" >> "$master_adoc"
                fi
              done
              cat  "$dir/master-raw.adoc"
              echo "$master_adoc"

              asciidoctor "$master_adoc"
              asciidoctor-reducer "$master_adoc" > "$dir/master.adoc" 

              echo "## [$cleaned_dir] ($dir/master.html)" >> README-HTML.md
              echo "## [$cleaned_dir] ($dir/master.adoc)" >> README.md
              asciidoctor **/*.adoc

              for html_file in $(find "$dir" -name "*.html" | sort); do
                if [ -f "$html_file" ]; then
                  if ! echo "$html_file" | grep -q "master.html" && ! echo "$html_file" | grep -q "master-raw.html"; then
                    clean_file=$(basename "$html_file")
                    echo "### [$clean_file]($html_file)" >> README-HTML.md
                  fi
                fi
              done

              for adoc_file in $(find "$dir" -name "*.adoc" | sort); do
                if [ -f "$adoc_file" ]; then
                  if ! echo "$adoc_file" | grep -q "master.adoc" && ! echo "$adoc_file" | grep -q "master-raw.adoc"; then
                    clean_file=$(basename "$adoc_file")
                    first_value="${clean_file%%-*}"
                    asciidoctor-reducer "$dir/$clean_file.adoc" > "$dir/$first_value.adoc" 
                    echo "### [$first_value]($dir/$clean_file.adoc)" >> README.md
                  fi
                fi
              done
            fi
          done

          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "github-action commit"
          git push origin main